/***
 * ===================================================================
 * @author      
 * @email       
 * @version     
 * @date        
 * @description 
 * ===================================================================
**/
@isTest
public class LookupManagementTest {
   
    @TestSetup
    static void setup(){
        
    }
    
    @IsTest
    static void calculateAllRollupsTest(){
        
        Test.startTest();
        Test.stopTest();
        
    }

    @IsTest
    static void setDefaultParentValuesTest(){
        
        Test.startTest();
        Test.stopTest();
        
    }

    @IsTest
    static void calculateRollupTest(){
        
        Test.startTest();
        Test.stopTest();
        
    }

    @IsTest
    static void createQueryStringTest(){
        
        Test.startTest();
        Test.stopTest();
        
    }


}